# Generated by Django 5.1.1 on 2024-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server01", "0013_attraction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attraction",
            name="description",
        ),
        migrations.AlterField(
            model_name="attraction",
            name="city",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="name",
            field=models.TextField(),
        ),
    ]
